### ISSUE TITLE
Issues running with custom resolver

### ISSUE THREAD

**Issue by dmitrif** [royalpinto/node-cares#1]
Hi!

Tried running with 0.12.7:

```
Assertion failed: (RB_EMPTY(&ares_tasks)), function ares_sockstate_cb, file ../src/cares_wrap.cc, line 293.
[1]    25162 abort      node test.js
```

Then with 0.10:

```
[1]    36100 segmentation fault  node test.js
```

Using the following test code:

```
    var resolver = new cares.Resolver({
        servers: [options.consulHost]
    });

    resolver.query('test.service.consul', {
        type: cares.NS_T_SRV
    }, function (err, response) {
        if (err) { throw err; }

        response.answer.forEach(function (a) {
            console.log(a);
        })
    })
```

**Comment by royalpinto** [comment]
Thanks for reporting the issue. I am not able to reproduce the issue, do you get this error when you try from a specific name server or from any name server ? If its from a specific name sever, may I know the name server so that I can reproduce this issue and fix.

**Comment by dmitrif** [comment]
Hi, @royalpinto 

I am running into this issue trying to hit a local consul instance. Easiest way to test it out is to use:

https://github.com/gliderlabs/docker-consul/tree/legacy
`docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap -ui-dir /ui`

Then to register a dummy service:
`curl -X POST -d '{"Address":"127.0.0.1", "Port": '8000', "Tags": ["http"], "Name": "sample-service"}' "http://127.0.0.1:8500/v1/agent/service/register"`

To de-register a dummy service:
`curl -X POST "http://127.0.0.1:8500/v1/agent/service/deregister/sample-service"`

A dig command to verify that the service registered correctly, before trying with node-cares:
`dig SRV @127.0.0.1 -p 8600 sample-service.service.consul`

Thank you.

**Comment by dmitrif** [comment]
Almost a month later testing again and finding the following behavior: If TCP/UDP ports are specified as `Number`'s then the test fails with `Segmentation Fault`. If a string, the execution plainly hangs.

**Comment by royalpinto** [comment]
Hi @dmitrif,

Sorry for the delayed response and thanks for the detailed explanation on how to reproduce the issue.
I have fixed both the issues in the newer version `1.0.2`. Please let me know if you are still facing issues.

Thanks

**Comment by dmitrif** [comment]
Sorry for delay on my part. It was working for a while, but now with the following code:

```
var cares = require('cares');

function discover(serviceName) {  
  var resolver = new cares.Resolver({
    servers: ['127.0.0.1'],
    udp_port: '8600',
    timeout: 250
  });

  resolver.query(
    '_'+ serviceName +'._http.service.consul', 
    {
      'class': cares.NS_C_IN,
      'type': cares.NS_T_SRV,
    },
    function (err, response) {
      if (err) { 
        console.error(err);
        return;
      }

      console.log(response);
    }
  );
};

discover('sample-service');
```

I am getting:
`{ [Error: Could not contact DNS servers]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  status: 11,
  syscall: 'queryGeneric' }`

Although the `dig` command is able to retrieve the info as needed.

**Comment by dmitrif** [comment]
Nvm, passing the port as an integer fixes the issue again.

**Comment by royalpinto** [comment]
Thanks 👍
